AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ing Java2 Lambda Function From Scratch Using SAM

Globals:
  Function:
    Timeout: 20
    Runtime: java8

Resources:
  Java2LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Java2LambdaFunction
      Handler: com.lambda.basics.Handler::handleRequest
      MemorySize: 512
      CodeUri: ./
      AutoPublishAlias: live
      Tracing: Active
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tags: {
              "Project": "AWS Java2 Lambda CI/CD",
              "Owner": "HD"
      }
